=== konradha/ae108-mirror/tests/schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string"
    },
    "executable": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "minItems": 1
    },
    "compare_stdout": {
      "type": "string",
      "enum": [
        "numeric",
        "text",
        "none"
      ],
      "default": "none"
    },
    "mpi_processes": {
      "type": "array",
      "default": "[1]",
      "items": {
        "type": "integer"
      }
    },
    "ae108_output": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "filename"
        ],
        "properties": {
          "filename": {
            "type": "string"
          },
          "xdmf_generator_flags": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "default": []
          }
        },
        "additionalProperties": false
      }
    },
    "args": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "default": []
    }
  },
  "required": [
    "executable"
  ],
  "additionalProperties": false
}

=== konradha/ae108-mirror/tests/examples/output/definition.json
{
  "$schema": "../../schema.json",
  "executable": [
    "examples",
    "ae108-examples-Output"
  ],
  "ae108_output": [
    {
      "filename": "output.ae108",
      "xdmf_generator_flags": [
        "--planar"
      ]
    }
  ],
  "compare_stdout": "text",
  "mpi_processes": [
    1,
    3
  ]
}
